apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-with-gradle-deployment
  labels:
    app: jwt-with-gradle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jwt-with-gradle
  template:
    metadata:
      labels:
        app: jwt-with-gradle
    spec:
      containers:
        - name: jwt-with-gradle
          image: razdeepak/jwt-security:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jwt-with-gradle
spec:
  type: NodePort
  selector:
    app: jwt-with-gradle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
